allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@intlify/core-base@11.4.12'
  - '@intlify/devtools-types@11.4.12'
  - '@intlify/message-compiler@11.4.12'
  - '@intlify/shared@11.4.12'
  - '@vue/compiler-core@3.5.43'
  - '@vue/compiler-dom@3.5.43'
  - '@vue/compiler-sfc@3.5.43'
  - '@vue/compiler-ssr@3.5.43'
  - '@vue/reactivity@3.5.43'
  - '@vue/runtime-core@3.5.43'
  - '@vue/runtime-dom@3.5.43'
  - '@vue/server-renderer@3.5.43'
  - '@vue/shared@3.5.43'
  - vue-i18n@11.4.12
  - vue@3.5.43
onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
