name: Publish on NPM and GitHub Packages

on:
    # Runs on release publish
    release:
        types: [published]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2.2.2
              with:
                  version: 7
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'
            - name: Install dependencies
              run: pnpm install
            - name: Build release
              run: pnpm build
            - name: Bump version with release tag name
              run: pnpm version --no-git-tag-version ${{ github.event.release.tag_name }}
            - name: Pack package
              run: pnpm pack
            - name: Upload artifact
              uses: actions/upload-artifact@v3
              with:
                  name: package
                  path: '*.tgz'
    publish-npm:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v3
              with:
                  name: package
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org/
            - run: npm publish $(ls *.tgz) --access=public --tag ${{ github.event.release.prerelease && 'next' || 'latest'}}
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

    publish-gpr:
        needs: build
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v3
              with:
                  name: package
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  registry-url: https://npm.pkg.github.com/
            - run: npm publish $(ls *.tgz) --access=public --tag ${{ github.event.release.prerelease && 'next' || 'latest'}}
              env:
                  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
